version: "3.8"

networks:
  finease_network:
    external: true  # Use existing external network

services:
  wallet-service:
    build:
      context: ./wallet-service
      dockerfile: Dockerfile
    container_name: wallet-service
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mypostgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_APPLICATION_NAME=wallet-service
      - APP_SECRET_KEY=my-secret-key
    networks:
      - finease_network
    depends_on:
      mypostgres:
        condition: service_healthy  # Ensure database is ready before starting the service
    ports:
      - "8080:8080"

  atm:
    build:
      context: ./atm
      dockerfile: Dockerfile
    container_name: atm-service
    restart: "no"
    working_dir: /app
    command: [ "tail", "-f", "/dev/null" ]  # Keeps the container running
    depends_on:
      wallet-service:
        condition: service_started
    networks:
      - finease_network

  mypostgres:
    image: postgres:latest
    container_name: mypostgres
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - finease_network
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
