### create account
POST http://localhost:8080/v2/accounts
Content-Type: application/json
application_id: your-application-id
api_key: your-api-key

{
  "account_ref": "unique-account-ref",
  "account_name": "New Account",
  "client_id": 123,
  "balance": 1000.00
}

### get all account
GET http://localhost:8080/v2/accounts
Content-Type: application/json
application-id: dHPexKO-6A06p6O5gYRNNA
api-key: 5165f39b85d44604aabcb0c4e5a8f80a2c9b4444c51e4b1797efbff0d2b273ed

### get account by reference_id
GET http://localhost:8080/api/v2/accounts/{account_ref}
Content-Type: application/json
application_id: your-application-id
api_key: your-api-key





