### Register a new user (Signup)
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "fullName": "john_doe",
  "email": "john.doe@example.com",
  "password": "SecurePassword123"
}

### Authenticate and Login User
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "SecurePassword123"
}
