### Test Create Client API (POST Request)
POST http://localhost:8080/api/v1/clients
Content-Type: application/json
secret_key: my-secret-key

{
  "client_name": "TestClient3"
}

### Test Deactivate Client API (PUT Request)
PUT http://localhost:8080/v1/clients/deactivate
Content-Type: application/json
secret_key: my-secret-key

{
  "client_name": "Valid Client",
  "application_id": "M3_EX2C3BLhDqPFCrbn0Rg",
  "api_key": "32088f53bfdb444a854ba1a8d3daf705404825aa88984f8aaa385d23e06932f5"
}

