###Transaction API
POST http://localhost:8080/v2/transactions
Content-Type: application/json
application-id: zMrC1R0MyaRAyRxRrTPZlA
api-key: 18673025e2954863875913d2e88588b080777e9038ef483e83413773f518df55
account-id:RFID1000000022

{
  "reference_id": "1234546789",
  "amount": 1000.00,
  "transaction_type": "TRANSFER",
  "recipient":"alice"
}